apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping-nginx
  name: shopping-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shopping-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
